services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: butterfly_room:prod
    container_name: butterfly_room-app
    working_dir: /app
    env_file:
      - ./.env.production
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      NODE_ENV: production
    restart: unless-stopped
