default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV.fetch(
          "DATABASE_URL",
          "postgres://postgres:postgres@db:5432/butterfly_room_development"
        ) %>

test:
  <<: *default
  url: <%= ENV.fetch(
          "DATABASE_URL_TEST",
          "postgres://postgres:postgres@db:5432/butterfly_room_test"
        ) %>

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] || "postgres://postgres:postgres@localhost:5432/dummy" %>

  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] || "postgres://postgres:postgres@localhost:5432/dummy" %>

  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] || "postgres://postgres:postgres@localhost:5432/dummy" %>

  cache:
    <<: *default
    url: <%= ENV["DATABASE_URL"] || "postgres://postgres:postgres@localhost:5432/dummy" %>
