- key: deepar_aviators
  name: サングラス
  url: /deepar/effects/aviators
  preview_filename: aviators_preview.svg
  enabled: true
  position: 0
  default: true
- key: deepar_lion
  name: ライオン
  url: /deepar/effects/lion
  preview_filename: lion_preview.svg
  enabled: true
  position: 1
  default: false
- key: deepar_koala
  name: コアラ
  url: /deepar/effects/koala
  preview_filename: koala_preview.svg
  enabled: true
  position: 2
  default: false
- key: deepar_dalmatian
  name: ダルメシアン
  url: /deepar/effects/dalmatian
  preview_filename: dalmatian_preview.svg
  enabled: true
  position: 3
  default: false
- key: deepar_galaxy_background
  name: ギャラクシー
  url: /deepar/effects/galaxy_background
  preview_filename: galaxy_background_preview.svg
  enabled: true
  position: 4
  default: false
- key: deepar_background_blur
  name: 背景ぼかし
  url: /deepar/effects/background_blur.deepar
  preview_filename: background_blur_preview.svg
  enabled: true
  position: 5
  default: false
- key: deepar_background_replacement
  name: 背景差し替え
  url: /deepar/effects/background_replacement.deepar
  preview_filename: background_replacement_preview.svg
  enabled: true
  position: 6
  default: false
